produtos = [
    ("Descanso de Panela / Suporte / Porta Tempero", "", "https://shp.ee/UVensRKg"),
    ("Cortina Luxo Para Sala 4,00m x 2,60m", "", "https://shp.ee/9MtB1dLD"),
    ("Cortina de Voil com Blackout 2,80 x 2,30", "", "https://shp.ee/piJy73M6"),
    ("Varal de Chão 3 Andares Dobrável", "", "https://shp.ee/zeahSZZz"),
    ("Painel Sala de Estar Para TV até 50", "", "https://shp.ee/cE9qHmqF"),
    ("Tapete para Banheiro Kit 3 Peças", "", "https://shp.ee/tz7SV7Cq"),
    ("Tapete Sala 2,00 x 1,50", "", "https://shp.ee/cKQmxABE"),
    ("Suporte Organizador Porta Controle Remoto", "", "https://shp.ee/g7QAWxi6"),
    ("Torneira de Cozinha Gourmet", "", "https://shp.ee/23C6BMYt"),
    ("Cuscuzeiro Crema 16cm", "", "https://shp.ee/nyKbqRkv"),
    ("Taça de Sobremesa Kit 6 Taças", "", "https://shp.ee/LL3biid5"),
    ("Boleira Queijeira Bambu Grande", "", "https://shp.ee/49vaXkPa"),
    ("Escorredor de Louça Duplo", "", "https://shp.ee/aKrZ589J"),
    ("Pote Dispenser Multiuso 1200ml", "", "https://shp.ee/vwzUXxCH"),
    ("2 Garrafas de Vidro 1L", "", "https://shp.ee/JXyUtvBT"),
    ("Garrafa Térmica Nórdica 1L", "", "https://shp.ee/XQw7wXFs"),
    ("Sapateira Buenos Aires 3 Portas", "", "https://shp.ee/mf6x4GzS"),
    ("Kit Taças de Vidro", "", "https://shp.ee/f9ZtK2iM"),
    ("Sanduicheira Britânia Antiaderente", "", "https://shp.ee/z4G8n8t9"),
    ("Air Fryer Philco 15L", "", "https://shp.ee/it4Prq3u"),
    ("Liquidificador Mondial Turbo Power", "", "https://shp.ee/hbY3KWSU"),
    ("Porta Temperos Industrial 5 Peças", "", "https://shp.ee/SDAPtELH"),
    ("Kit 4 Utensílios Cozinha Inox", "", "https://shp.ee/ghTVgxKN"),
    ("Conjunto de Formas Assadeiras 4 Peças", "", "https://shp.ee/WF8vd1s3"),
    ("Kit 15 Potes Variados", "", "https://shp.ee/Tu3ihFoL"),
    ("Kit 3 Potes de Vidro Hermético", "", "https://shp.ee/7WgMWAfs"),
    ("Vassoura Mágica Rodo Multifuncional", "", "https://shp.ee/CQaQkeMr"),
    ("Kit Banheiro 4 Peças Luxo", "", "https://shp.ee/w8pJW2rt"),
    ("Panela de Pressão 4,5L Cerâmica", "", "https://shp.ee/qdrwN8CR"),
    ("Jogo de Toalha 2 Banho e 2 Rosto", "", "https://shp.ee/HcPC3pqw"),
    ("Manta Cobre Leito Canelado", "", "https://shp.ee/L9MzV1sH"),
    ("Edredom Casal Queen Dupla Face", "", "https://shp.ee/MfAirvpH"),
    ("Jogo de Lençol Aconchegante", "", "https://shp.ee/YukV9xuo"),
    ("Kit Organizadores Herméticos Acrílico", "", "https://shp.ee/42Mp3zS2"),
    ("Tábua de Churrasco Grande", "", "https://shp.ee/pMw2Wxoe"),
    ("Kit 6 Peças Facas Profissional", "", "https://shp.ee/PWunPw6f"),
    ("Kit Escorredor Massa + Peneira Inox", "", "https://shp.ee/QgjHpmDN"),
    ("Jogo de Panelas Antiaderente", "", "https://shp.ee/aEKThWoW"),
    ("Jogo Faqueiro 25 Peças Nude", "", "https://shp.ee/kWeLqgAS"),
    ("Jogo 6 Copos Aruba Fumê", "", "https://shp.ee/TeTvwmRb"),
    ("Kit 6 Pratos Rasos Porcelana", "", "https://shp.ee/7Hbmh9GC"),
]